## Dependencias

In [12]:
import numpy as np
import pandas as pd 

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

from varclushi import VarClusHi

import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf

cf.go_offline()

## Datos

In [2]:
data = load_iris()

In [4]:
X,y = data['data'],data['target']
X = pd.DataFrame(X,columns=data['feature_names'])
y = pd.Series(y)

In [6]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Partición

In [9]:
Xt,Xv,yt,yv = train_test_split(X,y,test_size=0.3,random_state=123)
Xt.reset_index(drop=True,inplace=True)
Xv.reset_index(drop=True,inplace=True)
yt.reset_index(drop=True,inplace=True)
yv.reset_index(drop=True,inplace=True)
Xt.shape,Xv.shape,yt.shape,yv.shape

((105, 4), (45, 4), (105,), (45,))

## AEX

In [20]:
Xt.corr()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.159410           0.873227   
sepal width (cm)           -0.159410          1.000000          -0.442854   
petal length (cm)           0.873227         -0.442854           1.000000   
petal width (cm)            0.804330         -0.367006           0.958673   

                   petal width (cm)  
sepal length (cm)          0.804330  
sepal width (cm)          -0.367006  
petal length (cm)          0.958673  
petal width (cm)           1.000000

In [23]:
varc = Xt.columns.tolist()
fuera = ['petal width (cm)']
varc = [v for v in varc if v not in fuera]
Xt.drop(fuera,axis=1,inplace=True)
Xv.drop(fuera,axis=1,inplace=True)
len(varc)

3

In [33]:
aux = Xt.merge(yt.to_frame().astype(str), left_index=True, right_index=True)
aux[0] = aux[0].astype(int).map({0:'setosa',1:'versicolor',2:'virginica'})
aux.columns = varc+['target']
aux.iplot(kind='scatter3d',x=varc[0], y=varc[1], z=varc[2], categories='target', title='Iris')


## Aprendizaje

In [34]:
ad = LinearDiscriminantAnalysis()
ad.fit(Xt,yt)

LinearDiscriminantAnalysis()

In [36]:
print(confusion_matrix(yt,ad.predict(Xt)))

print(confusion_matrix(yv,ad.predict(Xv)))

[[32  0  0]
 [ 0 38  2]
 [ 0  2 31]]
[[18  0  0]
 [ 0 10  0]
 [ 0  2 15]]


In [37]:
print(accuracy_score(yt,ad.predict(Xt)))
print(accuracy_score(yv,ad.predict(Xv)))

0.9619047619047619
0.9555555555555556
